[package]
name = "paap-configurator"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "paap-configurator"
path = "src/main.rs"

[dependencies]
serialport = "4.5"
log = "0.4"
env_logger = "0.11"
eframe = "0.29"
confy = "0.6"
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
opt-level = 0           # No optimization.
debug = true            # Full debug info.
strip = false           # Keep symbols.
debug-assertions = true
overflow-checks = true
incremental = true      # Faster recompilation.

[profile.release]
opt-level = 'z'               # Optimize for size.
lto = true                    # Enable Link Time Optimization.
codegen-units = 1             # Better optimization.
strip = true                  # Strip symbols.
panic = 'abort'               # Smaller panic handler.
